-- Create invites table
create table if not exists invites (
  id bigint generated by default as identity primary key,
  token uuid not null unique,
  member_id bigint references members(id) not null,
  club_id bigint references clubs(id) not null,
  expires_at timestamp with time zone not null,
  created_by uuid references auth.users(id) not null,
  created_at timestamp with time zone default now() not null
);

-- Add RLS policies for invites table
alter table invites enable row level security;

-- Allow club admins to create invites
create policy "Club admins can create invites"
  on invites
  for insert
  to authenticated
  with check (
    exists (
      select 1 from clubs c
      inner join users u on u.club_id = c.id
      inner join roles r on r.id = u.role_id
      where c.id = invites.club_id
      and u.id = auth.uid()::text
      and r.name = 'admin'
    )
  );

-- Allow club admins to view invites for their club
create policy "Club admins can view invites"
  on invites
  for select
  to authenticated
  using (
    exists (
      select 1 from clubs c
      inner join users u on u.club_id = c.id
      inner join roles r on r.id = u.role_id
      where c.id = invites.club_id
      and u.id = auth.uid()::text
      and r.name = 'admin'
    )
  );
