-- =====================================================
-- LOOPLE TWO-STAGE MEMBERSHIP MIGRATION PLAN
-- =====================================================
-- This migration transforms your existing schema to support:
-- 1. Two-stage membership (onboarding → payment → activation)
-- 2. Admin payment management dashboard
-- 3. Secure tenant isolation
-- 4. Multi-club user support
-- 5. Family billing consolidation

-- =====================================================
-- PHASE 1: URGENT SECURITY FIXES
-- =====================================================

-- FIX: Clubs should NOT be viewable by everyone
-- This is a critical security issue - removes public club visibility
DROP POLICY IF EXISTS "Clubs are viewable by anyone" ON clubs;

-- Replace with tenant-isolated club viewing
CREATE POLICY "Clubs are viewable by members and owners" ON clubs FOR SELECT TO public
USING (
  -- Club owners can see their clubs
  (auth.uid())::text = owner_id 
  OR 
  -- Members can see their clubs
  EXISTS (
    SELECT 1 FROM members m 
    WHERE m.club_id = clubs.id 
    AND m.user_id = (auth.uid())::text
  )
  OR 
  -- Service role bypass
  (auth.jwt() ->> 'role') = 'service_role'
);

-- =====================================================
-- PHASE 2: ADD MISSING PAYMENT FIELDS
-- =====================================================

-- Add payment status tracking to members table
ALTER TABLE members ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'unpaid'
  CHECK (payment_status IN ('unpaid', 'paid', 'overdue', 'refunded'));

ALTER TABLE members ADD COLUMN IF NOT EXISTS dues_paid_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS dues_amount DECIMAL(10,2);
ALTER TABLE members ADD COLUMN IF NOT EXISTS next_payment_due TIMESTAMP WITH TIME ZONE;

-- Add approval workflow fields
ALTER TABLE members ADD COLUMN IF NOT EXISTS approved_by TEXT REFERENCES users(id);
ALTER TABLE members ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS membership_notes TEXT;

-- Update membership_status enum to include our workflow states
DO $$
BEGIN
  -- First, remove the default constraint
  ALTER TABLE members 
    ALTER COLUMN membership_status DROP DEFAULT;

  -- Drop and recreate enum with all needed values
  ALTER TYPE membership_status_enum RENAME TO membership_status_enum_old;
  
  CREATE TYPE membership_status_enum AS ENUM (
    'pending',    -- User invited/joined but not approved
    'approved',   -- Admin approved but not paid
    'active',     -- Paid and full member
    'suspended',  -- Temporarily disabled
    'expired'     -- Membership expired
  );
  
  -- Update column to use new enum
  ALTER TABLE members 
    ALTER COLUMN membership_status TYPE membership_status_enum 
    USING membership_status::text::membership_status_enum;
  
  -- Add back the default value
  ALTER TABLE members 
    ALTER COLUMN membership_status SET DEFAULT 'pending'::membership_status_enum;
  
  -- Drop old enum
  DROP TYPE membership_status_enum_old;
END $$;

-- Add Stripe Connect status fields to clubs
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS stripe_account_status TEXT DEFAULT 'pending'
  CHECK (stripe_account_status IN ('pending', 'active', 'restricted', 'inactive'));
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS stripe_capabilities JSONB DEFAULT '{}';
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS membership_fee_amount DECIMAL(10,2);
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS membership_fee_frequency TEXT DEFAULT 'annual'
  CHECK (membership_fee_frequency IN ('monthly', 'quarterly', 'annual', 'seasonal'));

-- =====================================================
-- PHASE 3: CREATE MISSING TABLES
-- =====================================================

-- Create payments audit table
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
  user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  
  -- Payment details
  stripe_payment_intent_id TEXT,
  stripe_charge_id TEXT,
  amount DECIMAL(10,2) NOT NULL,
  currency TEXT DEFAULT 'USD',
  description TEXT,
  
  -- Payment status and metadata
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'succeeded', 'failed', 'canceled', 'refunded')),
  payment_method TEXT, -- 'card', 'ach', 'cash', etc.
  payment_date TIMESTAMP WITH TIME ZONE,
  refunded_amount DECIMAL(10,2) DEFAULT 0,
  refund_reason TEXT,
  
  -- Platform fee tracking (for revenue sharing)
  platform_fee_amount DECIMAL(10,2),
  club_net_amount DECIMAL(10,2),
  
  -- Metadata and audit
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create event registrations table (missing from current schema)
CREATE TABLE IF NOT EXISTS event_registrations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  
  -- Registration details
  registration_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'registered'
    CHECK (status IN ('registered', 'confirmed', 'canceled', 'waitlisted', 'attended')),
  
  -- Payment tracking for this specific registration
  payment_required BOOLEAN DEFAULT TRUE,
  payment_amount DECIMAL(10,2),
  payment_status TEXT DEFAULT 'pending'
    CHECK (payment_status IN ('pending', 'paid', 'refunded')),
  payment_id BIGINT REFERENCES payments(id),
  
  -- Registration metadata
  registration_data JSONB DEFAULT '{}', -- Custom form fields
  notes TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Ensure one registration per member per event
  UNIQUE(event_id, member_id)
);

-- Create units table for family billing (as discussed)
CREATE TABLE IF NOT EXISTS units (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  
  -- Billing information
  billing_status VARCHAR(20) DEFAULT 'active'
    CHECK (billing_status IN ('active', 'suspended', 'inactive')),
  billing_email VARCHAR(255),
  billing_phone VARCHAR(20),
  billing_address JSONB,
  
  -- Audit fields
  created_by TEXT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create unit_members table for family relationships
CREATE TABLE IF NOT EXISTS unit_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id UUID NOT NULL REFERENCES units(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Role within the family unit
  role VARCHAR(20) DEFAULT 'member'
    CHECK (role IN ('admin', 'coadmin', 'member', 'child')),
  
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Ensure one user per unit
  UNIQUE(unit_id, user_id)
);

-- Link members to units for family billing
ALTER TABLE members ADD COLUMN IF NOT EXISTS unit_id UUID REFERENCES units(id);

-- =====================================================
-- PHASE 4: CREATE INDEXES FOR PERFORMANCE
-- =====================================================

-- Payment status queries (admin dashboard)
CREATE INDEX IF NOT EXISTS idx_members_payment_status ON members(club_id, payment_status);
CREATE INDEX IF NOT EXISTS idx_members_membership_status ON members(club_id, membership_status);
CREATE INDEX IF NOT EXISTS idx_members_next_payment_due ON members(next_payment_due) WHERE next_payment_due IS NOT NULL;

-- Multi-tenant performance
CREATE INDEX IF NOT EXISTS idx_payments_club_id ON payments(club_id);
CREATE INDEX IF NOT EXISTS idx_payments_member_id ON payments(member_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at);

-- Event registration performance
CREATE INDEX IF NOT EXISTS idx_event_registrations_event_id ON event_registrations(event_id);
CREATE INDEX IF NOT EXISTS idx_event_registrations_member_id ON event_registrations(member_id);
CREATE INDEX IF NOT EXISTS idx_event_registrations_status ON event_registrations(status);

-- Family unit performance
CREATE INDEX IF NOT EXISTS idx_unit_members_unit_id ON unit_members(unit_id);
CREATE INDEX IF NOT EXISTS idx_unit_members_user_id ON unit_members(user_id);
CREATE INDEX IF NOT EXISTS idx_members_unit_id ON members(unit_id);

-- =====================================================
-- PHASE 5: UPDATE RLS POLICIES FOR TWO-STAGE MEMBERSHIP
-- =====================================================

-- Add RLS to new tables
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE units ENABLE ROW LEVEL SECURITY;
ALTER TABLE unit_members ENABLE ROW LEVEL SECURITY;

-- Payments policies
CREATE POLICY "Payments are manageable by club owners" ON payments FOR ALL TO public
USING (
  EXISTS (
    SELECT 1 FROM clubs c 
    WHERE c.id = payments.club_id 
    AND c.owner_id = (auth.uid())::text
  )
  OR (auth.jwt() ->> 'role') = 'service_role'
);

CREATE POLICY "Users can view their own payments" ON payments FOR SELECT TO public
USING (
  user_id = (auth.uid())::text
  OR EXISTS (
    SELECT 1 FROM members m 
    WHERE m.id = payments.member_id 
    AND m.user_id = (auth.uid())::text
  )
);

-- Event registrations policies
CREATE POLICY "Event registrations are manageable by club owners" ON event_registrations FOR ALL TO public
USING (
  EXISTS (
    SELECT 1 FROM events e 
    JOIN clubs c ON c.id = e.club_id 
    WHERE e.id = event_registrations.event_id 
    AND c.owner_id = (auth.uid())::text
  )
  OR (auth.jwt() ->> 'role') = 'service_role'
);

CREATE POLICY "Members can view registrations in their clubs" ON event_registrations FOR SELECT TO public
USING (
  EXISTS (
    SELECT 1 FROM events e 
    JOIN members m ON m.club_id = e.club_id 
    WHERE e.id = event_registrations.event_id 
    AND m.user_id = (auth.uid())::text
  )
);

-- Units policies
CREATE POLICY "Unit admins can manage their units" ON units FOR ALL TO public
USING (
  created_by = (auth.uid())::text
  OR EXISTS (
    SELECT 1 FROM unit_members um 
    WHERE um.unit_id = units.id 
    AND um.user_id = (auth.uid())::text 
    AND um.role IN ('admin', 'coadmin')
  )
  OR (auth.jwt() ->> 'role') = 'service_role'
);

-- Unit members policies
CREATE POLICY "Unit members are manageable by unit admins" ON unit_members FOR ALL TO public
USING (
  EXISTS (
    SELECT 1 FROM units u 
    WHERE u.id = unit_members.unit_id 
    AND (
      u.created_by = (auth.uid())::text
      OR EXISTS (
        SELECT 1 FROM unit_members um2 
        WHERE um2.unit_id = u.id 
        AND um2.user_id = (auth.uid())::text 
        AND um2.role IN ('admin', 'coadmin')
      )
    )
  )
  OR (auth.jwt() ->> 'role') = 'service_role'
);

-- =====================================================
-- PHASE 6: ADD PAYMENT-BASED ACCESS RESTRICTIONS
-- =====================================================

-- Update events policy to restrict paid events for unpaid members
DROP POLICY IF EXISTS "Events are viewable by club members" ON events;

CREATE POLICY "Events are viewable by club members with payment restrictions" ON events FOR SELECT TO public
USING (
  EXISTS (
    SELECT 1 FROM members m 
    WHERE m.club_id = events.club_id 
    AND m.user_id = (auth.uid())::text
    AND (
      -- Free events: all approved members can see
      (events.price_member = 0 OR events.price_member IS NULL)
      OR 
      -- Paid events: only active (paid) members can see
      (events.price_member > 0 AND m.membership_status = 'active' AND m.payment_status = 'paid')
      OR
      -- Club owners can always see events
      EXISTS (
        SELECT 1 FROM clubs c 
        WHERE c.id = events.club_id 
        AND c.owner_id = (auth.uid())::text
      )
    )
  )
);

-- =====================================================
-- PHASE 7: CREATE HELPER FUNCTIONS
-- =====================================================

-- Function to check if a member's dues are current
CREATE OR REPLACE FUNCTION is_member_dues_current(member_id_param BIGINT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM members m
    WHERE m.id = member_id_param
    AND m.payment_status = 'paid'
    AND (m.next_payment_due IS NULL OR m.next_payment_due > NOW())
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get unpaid members for admin dashboard
CREATE OR REPLACE FUNCTION get_unpaid_members(club_id_param BIGINT)
RETURNS TABLE(
  member_id BIGINT,
  member_name TEXT,
  email TEXT,
  days_overdue INTEGER,
  amount_due DECIMAL(10,2)
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    m.id,
    (m.first_name || ' ' || m.last_name) as member_name,
    m.email,
    CASE 
      WHEN m.next_payment_due IS NOT NULL 
      THEN EXTRACT(days FROM (NOW() - m.next_payment_due))::INTEGER
      ELSE 0
    END as days_overdue,
    COALESCE(m.dues_amount, 0) as amount_due
  FROM members m
  WHERE m.club_id = club_id_param
  AND m.membership_status IN ('approved', 'active')
  AND m.payment_status IN ('unpaid', 'overdue')
  ORDER BY m.next_payment_due ASC NULLS LAST;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- PHASE 8: UPDATE TRIGGERS FOR AUTOMATION
-- =====================================================

-- Auto-update timestamp triggers
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add update triggers to new tables
CREATE TRIGGER update_payments_updated_at BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_event_registrations_updated_at BEFORE UPDATE ON event_registrations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_units_updated_at BEFORE UPDATE ON units
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- PHASE 9: DATA MIGRATION (IF NEEDED)
-- =====================================================

-- Set existing members to 'approved' status if they were 'active'
UPDATE members 
SET membership_status = 'approved'::membership_status_enum 
WHERE membership_status = 'active'::membership_status_enum 
AND payment_status = 'unpaid';

-- Keep existing active members as active if they have payment data
UPDATE members 
SET membership_status = 'active'::membership_status_enum 
WHERE membership_status = 'active'::membership_status_enum 
AND payment_status = 'paid';

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================

-- Verify the migration
SELECT 'Migration completed successfully! Your schema now supports:' as status;
SELECT '✅ Two-stage membership workflow (pending → approved → active)' as feature;
SELECT '✅ Payment status tracking and admin dashboard queries' as feature;
SELECT '✅ Secure tenant isolation (fixed club visibility)' as feature;
SELECT '✅ Family billing with units system' as feature;
SELECT '✅ Event access restrictions based on payment status' as feature;
SELECT '✅ Complete audit trail for payments' as feature; 